### PR TITLE
Move log.py to SensibleFormatter and SensibleFilter

### PR DESCRIPTION
**Pull request by Samwalton9**
I'll be honest I don't understand enough about lithoxyl this to know why this was required, but I couldn't start a local version of the app without these changes. Struggled to find any documentation of (non-sensible) Formatter or ThresholdFilter in lithoxyl docs.

### CODE REVIEW

**Comment by Samwalton9** [comment]
Also, filled out requirements.txt with the various pieces I needed to install. There could be more to add; I don't yet have a fully functioning version set up.

**Comment by mahmoud** [comment]
Hey Sam! Thanks for jumping in! Yeah, Lithoxyl is definitely underdocumented, and Hatnote stuff tends to very-early-adopt my projects (they're often written with Hatnote in mind, after all). 

I think you totally figured out the write thing to do; Lithoxyl renamed these types at one point. We totally should have had a requirements.txt with versions pinned. In fact, I think that's my main feedback for this PR: if you can, lock in versions like `lithoxyl==0.4.1` for some extra stability.

Quick question, are you testing these changes on your own labs account? If you have a particular application in mind, I'm happy to help. I'm mhashemirc on freenode, feel free to PM!

**Comment by Samwalton9** [comment]
Ah, awesome! I assumed that was the case but didn't spend all that much time trying to figure it out.

Great suggestion, we should definitely clarify versions on toolforge.

I was actually just about to request a new project on toolforge for testing purposes. Thanks! I'll drop you a message if I need any help with this.

**Comment by Samwalton9** [comment]
So in case it's not clear, this shouldn't be merged without an update of lithoxyl, but that should probably happen. Mahmoud, did any functionality change on the elements used here to the extent that you think this would break?

**Comment by Samwalton9** [comment]
Will re-open a more comprehensive pull request since I was working on master.

**Pull request closed without merging**
